# Entry point para la API
GET http://localhost:3000

###

# Devolver todos los highscores
GET http://localhost:3000/api/highscores

###

# Agregar un nuevo highscore
PUT http://localhost:3000/api/highscores
x-api-key:TU_API_KEY
Content-Type: application/json

{
    "gamertag": "MAYU",
    "points": 900,
    "shots": 90,
    "destroyedEnemies": 9,
    "destroyedBosses": 9,
    "gameTime": 900
}